import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import {
  Chart,
  CategoryScale,
  LinearScale,
  LineElement,
  PointElement,
  Filler,
} from "chart.js";


const plusJakartaSans = localFont({ src: './PlusJakartaSans-VariableFont_wght.ttf', 
  variable: "--font-plus-jakarta-san",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

Chart.register(CategoryScale, LinearScale, LineElement, PointElement, Filler);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
